
#*************** particle filter parameters ************************

#number of particles per target
num_particles: 500

#when a new filter/target is launched, XY space is sampled along init_delta_xy from the first detection point [m]
init_delta_xy: 0.4

#when a new filter/target is launched, VxVy space is sampled along init_delta_vxy from 0 [m/s]
init_delta_vxy: 2.0

#resampling standard deviation applied at the end of each filter iteration along XY dimensions [m]
sigma_resampling_xy: 0.01

#ratio of target velocity to compute resampling standard deviation applied at resampling step along VxVy dimensions [·]
sigma_ratio_resampling_vxy: 0.1
#sigma_ratio_resampling_vxy: 0.2 

#minimum value for standard deviation applied at resampling step along VxVy dimensions [m/s]
sigma_min_resampling_vxy: 0.1

#person radius used in LEG matching functions. Smaller the radius, more precise should be detections [m]
person_radius_legs: 0.4

#person radius used in BODY and FACES matching functions. Smaller the radius, more precise should be detections [m]
person_radius_body: 0.3

#LEG, BODY and BODY3D matching function parameters. 
matching_legs_alpha: 0.1
matching_legs_beta: 10
matching_bearing_alpha: 0.4
matching_bearing_beta: 10
matching_body3d_alpha: 0.2
matching_body3d_beta: 10


#****************** tracker parameters *********************************

#node rate [hz]
tracker_rate: 20.0

#If targets closer than this distance, merging function is called [m]
minimum_distance_between_people: 0.3

#Lower probabilities are treated as ZERO
minimum_association_prob: 0.00001

#detections farther than this distance are ignored [m]
max_detection_distance_accepted: 5

#detections closer than this distance are ignored [m]
min_detection_distance_accepted: 0.1

#leg detections with azimut greater/smaller than this/-this are ignored [deg]
max_detection_azimut_accepted: 90

#If a target, not in occlusion, remains max_consecutive_uncorrected_iterations without having associated any detection, the target is deleted
max_consecutive_uncorrected_iterations: 40

# a CANDIDATE target requires minimum_iterations_to_be_target to be considered as a LEGGED target
minimum_iterations_to_be_target: 4

# a LEGGED target requires minimum_iterations_to_be_visually_confirmed iterations with FACE, BODY or BODY3D detections associated, to be considered as VISUALLY_CONFIRMED
minimum_iterations_to_be_visually_confirmed: 3

# a VISUALLY_CONFIRMED target requires minimum_iterations_to_be_friend more iterations with FACE, BODY or BODY3D detections associated, to be considered as a FRIEND
minimum_iterations_to_be_friend: 3


#****************** ROS node options *************************************

#verbose mode. 0->Off, 1->On
verbose_mode: 0

#Log to file: 0->no, 1->yes
log_to_file: 1

#Publish visualization markers corresponding to body detections , 0->Off, 1->On
view_body_detections: 1

#Publish visualization markers of a subset of particles. 0->Off, 1->On
view_particles: 0



# video at: recordmydesktop --no-cursor -x 400 -y 190 --width 950 --height 570 
